sudo : required
language: generic

services :
  - docker

# Creating image to run test before creating prod build
before_install :
  - docker build -t devalseth2706/react-test -f ./client/Dockerfile.dev ./client

# Running test cases for all the project before creating production build
scripts :
  - docker run -e CI=true devalseth2706/react-test npm test

# Creating images for production after test
after_success :
  - docker build -t devalseth2706/multi-client ./client
  - docker build -t devalseth2706/multi-nginx ./nginx
  - docker build -t devalseth2706/multi-server ./server
  - docker build -t devalseth2706/multi-worker ./worker
# Login to Docker Hub to push the images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# After Login push all the build images to Docker hub
  - docker push devalseth2706/multi-client    
  - docker push devalseth2706/multi-nginx    
  - docker push devalseth2706/multi-server    
  - docker push devalseth2706/multi-worker    



